#!/usr/bin/python3
def best_score(a_dictionary):
    if len(a_dictonary) == 0:
        return (None)
    bk = None
    f = 0
    for i in a_dictionary:
        if f == 0:
            bk = i
            f = 1
        else:
            if a_dictionary[i] > a_dictionary[bk]:
                bk = i
                f = 1
    return (bk):
